@include('EssencesSite::component.header')
@include('EssencesSite::component.nav')
@include('EssencesSite::component.top-cart')
@include('EssencesSite::component.product-detail')
@include('EssencesSite::component.footer')