@include('EssencesSite::component.header')
@include('EssencesSite::component.nav')
@include('EssencesSite::component.top-cart')
@include('EssencesSite::component.shop-slider')
@include('EssencesSite::component.shop-side-bar')
@include('EssencesSite::component.search')
@include('EssencesSite::component.footer')