@include('EssencesSite::component.header')
@include('EssencesSite::component.nav')
@include('EssencesSite::component.top-cart')
@include('EssencesSite::component.wish')
@include('EssencesSite::component.footer')